import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Karisimbi Portal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Kariasimbi Portal
        </h1>

        <div className={styles.grid}>
          <Link href="/account">
            <a className={styles.card}>
              <h2>Profile &rarr;</h2>
              <p>Generate or view security keys.</p>
            </a>
          </Link>
          
          <Link  href="/upload">
            <a className={styles.card}>
              <h2>Upload file &rarr;</h2>
              <p>Upload and encrypt files on s3.</p>
            </a>
          </Link>
        </div>
      </main>

      <footer className={styles.footer}>
          Powered by {'   '}
          <span className={styles.title}>
            Sam 17
          </span>
      </footer>
    </div>
  )
}
